//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VATDUNGPHONG
    {
        public string PhongID { get; set; }
        public string VatDungID { get; set; }
        public int SoLuongBanDau { get; set; }
        public int SoLuongHienTai { get; set; }
        public string TrangThaiVatDungID { get; set; }
    
        public virtual LOAIVATDUNG LOAIVATDUNG { get; set; }
        public virtual PHONG PHONG { get; set; }
        public virtual TRANGTHAIVATDUNG TRANGTHAIVATDUNG { get; set; }
    }
}
