//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL.DAL
{
    using System;
    
    public partial class func_XemChiTietHoaDon_VatTu_Result1
    {
        public string TenVatDung { get; set; }
        public decimal SoLuongHu { get; set; }
        public decimal DonGia { get; set; }
    }
}
