//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADONVATDUNGPHONG
    {
        public string BookID { get; set; }
        public string PhongID { get; set; }
        public string TenVatDung { get; set; }
        public decimal SoLuongHu { get; set; }
        public decimal DonGia { get; set; }
    
        public virtual BOOK BOOK { get; set; }
        public virtual PHONG PHONG { get; set; }
    }
}
